In [17]:
import numpy as np


arr=np.array([1,23,2,4])
print(arr)

[ 1 23  2  4]


In [18]:
print(arr.shape)

(4,)


In [19]:
print(arr.reshape(2,2))

[[ 1 23]
 [ 2  4]]


In [20]:
#vectorized op
A =np.random.randint(0, 10, (3, 3))

B=np.arange(1,10).reshape((3,3))
B
A

array([[7, 9, 7],
       [7, 9, 4],
       [4, 9, 0]], dtype=int32)

In [21]:
b=A*B
print(b)

[[ 7 18 21]
 [28 45 24]
 [28 72  0]]


In [22]:
C=np.arange(10,19).reshape((3,3))
C

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [31]:
d=A-C
e=A/B
g=A*B
print(d)
print(e)
g

[[ -3  -2  -5]
 [ -6  -5 -11]
 [-12  -8 -18]]
[[7.         4.5        2.33333333]
 [1.75       1.8        0.66666667]
 [0.57142857 1.125      0.        ]]


array([[ 7, 18, 21],
       [28, 45, 24],
       [28, 72,  0]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
print(np.exp(A))
print(np.sqrt(A))

[[1.09663316e+03 8.10308393e+03 1.09663316e+03]
 [1.09663316e+03 8.10308393e+03 5.45981500e+01]
 [5.45981500e+01 8.10308393e+03 1.00000000e+00]]
[[2.64575131 3.         2.64575131]
 [2.64575131 3.         2.        ]
 [2.         3.         0.        ]]
